[2022-07-19 10:05:12,709] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple_dag.respond scheduled__2022-07-19T10:04:00+00:00 [queued]>
[2022-07-19 10:05:12,726] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple_dag.respond scheduled__2022-07-19T10:04:00+00:00 [queued]>
[2022-07-19 10:05:12,726] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 10:05:12,727] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-19 10:05:12,729] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-19 10:05:12,754] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): respond> on 2022-07-19 10:04:00+00:00
[2022-07-19 10:05:12,761] {standard_task_runner.py:52} INFO - Started process 6677 to run task
[2022-07-19 10:05:12,766] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'respond', 'scheduled__2022-07-19T10:04:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp2se3p9ut', '--error-file', '/tmp/tmpx21n8kmq']
[2022-07-19 10:05:12,768] {standard_task_runner.py:80} INFO - Job 334: Subtask respond
[2022-07-19 10:05:12,858] {task_command.py:370} INFO - Running <TaskInstance: simple_dag.respond scheduled__2022-07-19T10:04:00+00:00 [running]> on host 02ffb48252da
[2022-07-19 10:05:12,975] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-07-19T10:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-19T10:04:00+00:00
[2022-07-19 10:05:22,781] {logging_mixin.py:115} INFO - (2724, 1)
[2022-07-19 10:05:22,807] {python.py:173} INFO - Done. Returned value was: Greet Responded Again
[2022-07-19 10:05:22,910] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=respond, execution_date=20220719T100400, start_date=20220719T100512, end_date=20220719T100522
[2022-07-19 10:05:22,971] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
